### PR TITLE
quick2wire.gpio Pin classes now follow same API conventions as those in ...

### LINKED ISSUE #17: unexport does not reset GPIO to initial state (only removes it from device list)
Running this code results in the GPIO pin 11 still being set as OUTPUT and still being ON even after the unexport command:

Python code:
  from quick2wire.gpio import Pin
  Pin(11, "out")
  Pin(11).value = 1
  Pin(11).unexport()

Also using the unexport directly from shell with the command "gpio-admin unexport 11"
results in the same result.

Using any other GPIO library/driver that is available interprets this as GPIO pin nr 11 still being in use even though one has unexported the pin.

A partial solution is to manually set Pin 11 as an INPUT using command: "Pin(11, "in"), before using the unexport command, however this is not possible to implement together with the "with exported" statement in python.

### PR DESCRIPTION
**Pull request by npryce**
...the mcp23x17 module.

GPIO pins now have open() and close() methods and act as their own context managers. They export
the pin to userspace on open() and reset the pin state and unexport it on close().

THIS IS A BREAKING API CHANGE

Closes #17

### CODE REVIEW

**Comment by joewalnes** [comment]
Few minor nitpicks.

LGTM

**Comment by joewalnes** [comment]
I dunno... I still think quick2wire.gpio.gpio_breakout is kinda ugly. 

PEP8 also frowns upon the prefix: "The X11 library uses a leading X for all its public functions. In Python, this style is generally deemed unnecessary because attribute and method names are prefixed with an object, and function names are prefixed with a module name."

How about quick2wire.gpio.breakout instead?

**Comment by npryce** [comment]
I don't think the PEP8 warning applies here. I don't use gpio_ as a prefix
for everything in the module. Only to identify those GPIO pins that the Pi
header names as GPIO0..7.

I also think it's will be very rare to refer to the GPIO PinBank as
quick2wire.gpio.gpio - there's just no need to. This isn't Java: Python has
import as and from ... import to avoid that verbosity.

I think breakout is weirder.

with breakout.pin(1) as p:
    ...

That makes me think "which breakout?" Our board breaks out GPIO, i2C and
SPI.

--Nat

**Comment by joewalnes** [comment]
How about just quick2wire.gpio?

**Comment by npryce** [comment]
So would that be a class in the quick2wire module or a module?

What would the code look like?

**Comment by joewalnes** [comment]
Usage:

```
from quick2wire import gpio
with gpio.pin(1): ...
```

Implementation wise, something like:

In `quick2wire/gpio/__init__.py`:

```
pin = # delegate to real symbol
```

**Comment by npryce** [comment]
I think that's confusing when you import all the constants you need to work with GPIO pins

from quick2wire import gpio
from quick2wire.gpio import In, Out, ...

Maybe In, Out, etc. should be in Quick2Wire as well

but what about the I2C breakout, the SPI breakout, etc.?  It just begs the question why they are not all exported from quick2wire.  Should they be?

I think we really need to represent the platform separately from the I/O interface.

So then we'd have

from quick2wire.platform import gpio
from quick2wire.gpio import In, Out

pin = gpio.pin(1)

Would that be better?

**Comment by joewalnes** [comment]
It would be good to have i2c, spi, etc having a similar structure.

What's the difference between platform and gpio?

**Comment by npryce** [comment]
platform would export the PinBanks defined by the systems.  E.g. broadcom_soc, header_1, gpio on the Raspberry Pi.

gpio would contain the classes that implement the PinBanks.

But... I've come round to the idea of just calling it "pins".  E.g. "from quick2wire.gpio import pins" would import the GPIO breakout with pins P0...P8, while "from quick2wire.gpio import pi_header_1" would import the pinbank for header 1 on the Pi.

**Comment by npryce** [comment]
If there are no objections I'll rename gpio_breakout to pins & merge this in ASAP.

**Comment by joewalnes** [comment]
Sounds good.

**Pull request merged**
